### PR TITLE
Include path in the base url when resolving links and rels

### PR DESCRIPTION
**Pull request by hekard2l**
@AlexanderMS

### CODE REVIEW

**Comment by alex-murashkin** [comment]
On second look:
```
> url.resolve('http://localhost:3000/dev', 'abcd')
'http://localhost:3000/abcd'
> url.resolve('http://localhost:3000/dev/', 'abcd')
'http://localhost:3000/dev/abcd'
```
Don't we just need a trailing slash?

**Comment by hekard2l** [comment]
Hmmmm...

```
> url.resolve('http://localhost:3000/dev/', 'abcd')
'http://localhost:3000/dev/abcd'
> url.resolve('http://localhost:3000/dev/', '/abcd/afads')
'http://localhost:3000/abcd/afads'
> url.resolve('http://localhost:3000/dev/', 'http://localhost:5000/abcd/afads')
'http://localhost:5000/abcd/afads'
> url.resolve('http://localhost:3000/dev/', 'abcd/afads')
'http://localhost:3000/dev/abcd/afads'
```

I guess we could work around this and don't need this change?

**Comment by alex-murashkin** [comment]
It looks so to me. Need to test it end-to-end with the BFF though.

**Comment by hekard2l** [comment]
Well, our unit tests in the BFF cover the links and rels 😃, so we should be good. I have a branch where I've already made the changes to the BFF's tests

**Pull request closed without merging**
